#! /usr/bin/php
<?php 

define('APP_ROOT', realpath(dirname(__FILE__) . '/..'));
define('APP_ENV', getenv('APP_ENV') ? getenv('APP_ENV') : 'development');

require(APP_ROOT . '/vendor/pippa/lib/App.php');

App::boot();

switch($argv[1]) {

  case 'warm':
    App::$cache->warm();
    break;

  case 'clear':
    App::$cache->clear();
    break;

  default:
    throw new Exception("don't know how to {$argv[1]}");

}

