#! /usr/bin/php
<?php 

namespace Pippa;

define('APP_ROOT', realpath(dirname(__FILE__) . '/..'));
define('APP_ENV', getenv('APP_ENV') ? getenv('APP_ENV') : 'development');

require(APP_ROOT . '/vendor/pippa/app.php');

App::boot();

switch($argv[1]) {

  case 'secret':
    $secret = "371041ed72652baedca4b0e5bd8e43ceb1d6081c8feb895dc4fef9218ec3343589bb8de232ec5b9687e4f3b57fe132bbf9ea0badd3c1727c3002b22cb09739a4";
    echo "$secret\n";
    break;
  
  case 'migration':

    $migration_dir = App::root . '/db/migrate';
    if(!file_exists($migration_dir))
      mkdir($migration_dir, 0755, true);

    $name = $argv[2];
    $filename = $migration_dir . strftime("/%Y%m%d%H%M%S_$name.rb");
    $contents = <<<EOT
class $name < ActiveRecord::Migration

  self.up
  end

  self.down
  end

end
EOT;
    file_put_contents($filename, $contents);
    break;

  default:
    echo "unknown generator\n";
    break;
}
