#!/usr/bin/php
<?php

define('APP_ROOT', realpath(dirname(__FILE__) . '/..'));
define('APP_ENV', getenv('APP_ENV') ? getenv('APP_ENV') : 'production');

set_include_path(APP_ROOT . '/framework');

require_once('app.php');

\Framework\App::bootstrap();

#require_once('route.php');
#require_once('request.php');
#require_once('router.php');
#require_once('controller.php');

require_once(APP_ROOT . '/config/routes.php');

$test_files = glob(APP_ROOT . '/framework/test/*.php');

foreach($test_files as $test_file) {
  echo "\n*** RUNNING TESTS: $test_file ***\n\n";
  include($test_file);
}
